version: '3.7'

services:

  app:
    build:
      context: app
    hostname: app
    restart: always
    container_name: app
    environment:
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - NEO4J_HOST=${NEO4J_HOST}
      - NEO4J_PORT=${NEO4J_PORT}
      - NEO4J_USR=${NEO4J_USR}
      - NEO4J_PWD=${NEO4J_PWD}
      - LOCAL_DEPLOY=true
    ports:
      - 8086:8086