[tool.black]
line-length = 99
target-version = ["py36", "py37", "py38", "py39"]
skip-string-normalization = true
include = '\.py$'

[tool.isort]
profile = "black"
src_paths = ["app", "tests", "pipelines"]
line_length = 79
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true


[tool.bandit]
exclude_dirs = ["app/examples"]
skips = ["B608"]